// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculateRowSumsInCpp
NumericMatrix calculateRowSumsInCpp(NumericMatrix mat, IntegerMatrix cols);
RcppExport SEXP _scexpr_calculateRowSumsInCpp(SEXP matSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateRowSumsInCpp(mat, cols));
    return rcpp_result_gen;
END_RCPP
}
// countOccurrencesInCpp
IntegerMatrix countOccurrencesInCpp(NumericMatrix mat, IntegerMatrix cols);
RcppExport SEXP _scexpr_countOccurrencesInCpp(SEXP matSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(countOccurrencesInCpp(mat, cols));
    return rcpp_result_gen;
END_RCPP
}
// orderAndConcatenateStrings
std::vector<std::string> orderAndConcatenateStrings(Rcpp::CharacterMatrix mat);
RcppExport SEXP _scexpr_orderAndConcatenateStrings(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(orderAndConcatenateStrings(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scexpr_calculateRowSumsInCpp", (DL_FUNC) &_scexpr_calculateRowSumsInCpp, 2},
    {"_scexpr_countOccurrencesInCpp", (DL_FUNC) &_scexpr_countOccurrencesInCpp, 2},
    {"_scexpr_orderAndConcatenateStrings", (DL_FUNC) &_scexpr_orderAndConcatenateStrings, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_scexpr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
