#' Summarize Quantiles of a Seurat Metadata Variable
#'
#' Calculates selected quantiles for a numeric column in a Seurat object's
#' metadata. The result can be returned as a tibble or formatted as a
#' `knitr::kable()` table.
#'
#' @param obj A Seurat object.
#' @param meta_col A single character string naming a numeric column in
#'   `obj@meta.data`.
#' @param probs A numeric vector of probabilities between zero and one.
#'   Defaults to deciles from `0.1` through `1`.
#' @param decimals An optional non-negative integer specifying the number of
#'   decimal places to which quantile values are rounded. When `NULL`, values
#'   are not rounded.
#' @param names Character string controlling the quantile labels. Must be one
#'   of `"probs_cut"`, `"probs"`, or `"pct"`. `"probs_cut"` removes the leading
#'   zero from probabilities, `"probs"` uses the probabilities directly, and
#'   `"pct"` retains the percentage labels generated by [stats::quantile()].
#' @param kable Logical. If `TRUE`, return a table formatted with
#'   [knitr::kable()]. If `FALSE`, return a tibble.
#'
#' @return A `knitr_kable` object when `kable = TRUE`; otherwise, a tibble with
#'   columns `q` (quantile label) and the name supplied through `meta_col`
#'   (quantile value).
#'
#' @export
#'
#' @examples
#' \dontrun{
#' quantile_print(
#'   obj = seurat_object,
#'   meta_col = "nCount_RNA"
#' )
#'
#' quantile_print(
#'   obj = seurat_object,
#'   meta_col = "percent.mt",
#'   probs = c(0.25, 0.5, 0.75),
#'   decimals = 2,
#'   names = "pct",
#'   kable = FALSE
#' )
#' }
quantile_print <- function(
    obj,
    meta_col,
    probs = seq(0.1, 1, 0.1),
    decimals = NULL,
    names = c("probs_cut", "probs", "pct"),
    kable = TRUE
) {

  scexpr:::.ensure_packages(c(
    "knitr"
  ))
  names <- rlang::arg_match(names)

  qq <- stats::quantile(obj@meta.data[[meta_col]], probs = probs)

  if (names == "probs_cut") {
    names(qq) <- sub("^(-?)0\\.", "\\1.", probs)
  } else if (names == "probs") {
    names(qq) <- probs
  }

  if (!is.null(decimals)) {
    qq <- round(qq, decimals)
  }

  qqdf <- tibble::enframe(qq, name = "q", value = meta_col)

  if (kable) {
    knitr::kable(qqdf)
  } else {
    qqdf
  }
}
